### ISSUE TITLE
Question: Authenticate mutation return custom column from custom table?

### ISSUE THREAD

**Issue by ghost** [jamesedmonston/graphql-authentication#144]
Hi,

I have the following mutation which works just fine
```
      authenticate(email: $email, password: $password) {
        jwt
        jwtExpiresAt
        refreshToken
        refreshTokenExpiresAt
        user {
          ... on User {
            uid
            email
            firstName
            siteId
          }
        }
      }
    }
```

However, I would like to pull as well 2 custom columns that are in custom tables:

```
      authenticate(email: $email, password: $password) {
        jwt
        jwtExpiresAt
        refreshToken
        refreshTokenExpiresAt
        user {
          ... on User {
            uid
            email
            firstName
            siteId
            details {
              ... on UserDetails {
                inscriptionLastStep
                inscriptionVersion
              }
            }
          }
        }
      }
```

but I get this error

```
{
    "errors": [
        {
            "message": "Cannot query field \"details\" on type \"User\". Did you mean \"email\"?",
            "extensions": {
                "category": "graphql"
            },
            "locations": [
                {
                    "line": 13,
                    "column": 9
                }
            ]
        }
    ]
}
```

I don't see any way where I can extend the "User" type but in my app I do have a CustomUser for arguments, interfaces, mutations, queries and resolvers.

**Exemple**

```php
use craft\gql\interfaces\elements\User;

class CustomUser extends User {


    public static function getName(): string { /* ... */ }

    public static function getType($fields = null): Type { /* ... */ }

  
    public static function getFieldDefinitions(): array { /* ... */ }

    public static function getCustomFieldDefinitions(): array  { 
           /* ... */ 
           'details' => [
                'name' => 'details',
                'type' => UserDetails::getType(),
                'description' => "Details of an user"
            ],
            /* ... */ 
    }
}
```

**Comment by jamesedmonston** [comment]
Does this work when querying after the authenticate mutation? The plugin is just returning Craft's built-in `User` type here, so it should be working correctly: https://github.com/jamesedmonston/graphql-authentication/blob/develop/src/gql/Auth.php#L32

**Comment by LucaDelBuono** [comment]
I have a similar issue, it works fine in GraphiQL using the Full Schema but not the Public one.
This is my authentication:

```
mutation Authenticate {
  authenticate(
    email: "[USERNAME]",
    password: "[PASSWORD]"
  ) {
    jwt,
    jwtExpiresAt,
    refreshToken,
    refreshTokenExpiresAt,
    user {
      ...on User {
        user_show_vehicle {
          id,
          ...on vehicle_Entry{
            vehicle_make,
            vehicle_model
          }
        },
      }
      id,
      fullName
    }
  }
}
```

I tried fiddling with the Public Schema, enabling both `Query for users` and `Query for users in the “Members” user group` but still doesn't seem to work.
